import { Shield, Sword, Zap } from "lucide-react"

export const heroes = [
  {
    name: "Amadeus",
    role: "Rally Captain / Joiner",
    generation: "Gen 1 & Gen 2",
    description: "Best all-around hero for rallies. Use as captain or joiner for Lethality boost.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Amadeus-01Z2s5Rfm64ZAR3Mph48cA5dq6BfjR.png",
    icon: Sword,
    strengths: ["Rally Captain", "Rally Joiner", "Lethality Boost"],
    bestFor: ["Bear Hunt", "Swordland Showdown", "Alliance Championship"],
  },
  {
    name: "Jabel",
    role: "Rally Captain",
    generation: "Gen 1 & Gen 2",
    description: "Essential for rally captains. Avoid as rally joiner due to chance-based skill.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Jabel-HHTkp4CxXUTCE3g7t9LAW3rZBPHw3a.png",
    icon: Sword,
    strengths: ["Rally Captain", "High Damage", "F2P Friendly"],
    bestFor: ["Bear Hunt", "Swordland Showdown", "Viking Vengeance"],
  },
  {
    name: "Helga",
    role: "Rally Captain",
    generation: "Gen 1 & Gen 2",
    description: "Alternative rally captain with Lethality widget. Good when saving Amadeus for joining.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Helga-cgOf0m4Pu7oSOC5BRIdneYaBsyONBj.png",
    icon: Sword,
    strengths: ["Rally Captain", "Lethality Widget", "Solid Stats"],
    bestFor: ["Bear Hunt", "Swordland Showdown"],
  },
  {
    name: "Saul",
    role: "Rally Captain",
    generation: "Gen 1",
    description: "Good for Gen 1 rallies. Better than Quinn at 4 stars.",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Saul-4TTLz1V1S6j7tJtAOOvN355bxi2tSd.png",
    icon: Sword,
    strengths: ["Rally Captain", "Strong at 4 Stars", "Gen 1 Powerhouse"],
    bestFor: ["Bear Hunt", "Swordland Showdown", "Alliance Championship"],
  },
  {
    name: "Chenko",
    role: "Rally Joiner",
    generation: "All",
    description: "Provides +25% damage boost when first skill is Level 5. Must be first hero in formation.",
    image: "/chenko-hero-portrait-warrior.jpg",
    icon: Zap,
    strengths: ["Rally Joiner", "+25% Damage", "Lethality Boost"],
    bestFor: ["Bear Hunt", "Viking Vengeance"],
  },
  {
    name: "Yeonwoo",
    role: "Rally Joiner",
    generation: "All",
    description: "Gives 25% Lethality boost at 4 stars. Excellent rally joiner.",
    image: "/yeonwoo-hero-portrait-archer.jpg",
    icon: Zap,
    strengths: ["Rally Joiner", "+25% Lethality", "4 Star Power"],
    bestFor: ["Bear Hunt", "Viking Vengeance"],
  },
  {
    name: "Amane",
    role: "Rally Joiner",
    generation: "All",
    description: "Boosts Attack instead of Lethality. Still good rally joiner.",
    image: "/amane-hero-portrait-mage.jpg",
    icon: Zap,
    strengths: ["Rally Joiner", "Attack Boost", "Versatile"],
    bestFor: ["Bear Hunt", "Viking Vengeance"],
  },
  {
    name: "Howard",
    role: "Defense",
    generation: "Gen 1",
    description: "F2P defensive hero. Good for keeping at home during Viking Vengeance.",
    image: "/howard-hero-portrait-knight-defender.jpg",
    icon: Shield,
    strengths: ["Defense", "F2P Friendly", "Home Guard"],
    bestFor: ["Viking Vengeance", "City Defense"],
  },
  {
    name: "Quinn",
    role: "Support",
    generation: "Gen 1",
    description: "F2P support hero. Useful until you get better options.",
    image: "/quinn-hero-portrait-support-healer.jpg",
    icon: Shield,
    strengths: ["Support", "F2P Friendly", "Early Game"],
    bestFor: ["Bear Hunt", "Viking Vengeance"],
  },
]
